### ISSUE TITLE
Input / Output dimensions differ

### ISSUE THREAD

**Issue by nicenoize** [mp2893/medgan#19]
I am trying to reconstruct the evaluation process. To check the dimension-wise probability, I need a sample size that is as big as the number of patients from the dataset and generate a vector as input for my plot, if I understood correctly. The problem is, that my generated patients have a length of 906 each, whereas my input data has a length of 1071 each.
I determined the size of the vector for the generated patients by the shape of the numpy array that I receive as output.
I also compared the types dict size with the number of unique ICD9 codes (both 6985), so this does not seem to be the reason for losing dimensions.
If I switch from 3 digits to 5 digits, the dimensions stay the same size, shouldn't they go up to 6985? 
Any tips on how to fix this?

One more question: in your paper you plot 615 codes, where does this number derive from?

**Comment by mp2893** [comment]
Hi nicenoize,

That is very odd. The dimension size of the training data is decided automatically in line 377, and it is used throughout the entire training/generating phase.
Have you properly trained the model before you generated synthetic samples?
Also, could you try generating a smaller number of synthetic samples (e.g. 1000 samples), dump them, and check the dimension size?

As for 615 codes: That number is coming from having used the Sutter PAMF dataset, which is a different dataset than MIMIC-III.

Best,
Ed

**Comment by nicenoize** [comment]
Hello Ed,
thanks for your quick reply!
I found the issue and fixed the problem by changing convert_to_3digit_icd9(tokens[4][1:-1]) to convert_to_3digit_icd9(tokens[4]).
So it basically was the same problem again I had in the other issue I opened... 
Oddly I got the correct size when I used the Jupyter notebook instead of executing the script via Terminal. 

Best regards,
Sebastian
